//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EMPID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<double> Salary { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> DepID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
